spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/ai/**