spring.application.name=product-service


server.port = 8020

# ===============================
# LOG FILE CONFIG
# ===============================

# Folder where logs will be stored
logging.file.path=logs

# Name of log file
logging.file.name=logs/application.log

# Logging level
logging.level.root=INFO
logging.level.com.srb.demoForKafka=DEBUG

# Log pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


spring.profiles.active=local

kafka.topic.product-ai=PRODUCT-AI-TOPIC