eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# IMPORTANT (fix hostname issue)
eureka.instance.prefer-ip-address=true
# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.bootstrap-servers=localhost:9092
# Consumer Group
spring.kafka.consumer.group-id=AI-GROUP

# Offset behavior
spring.kafka.consumer.auto-offset-reset=earliest

# Key Deserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value Deserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Allow DTO packages
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.srb.product.model.Product
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3:latest
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.num-predict=100



spring.datasource.url=jdbc:mariadb://localhost:3308/spring_ai

spring.datasource.username=root
spring.datasource.password=root



spring.ai.vectorstore.mariadb.initialize-schema=false
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=1024
