spring.application.name=AUTH-SERVICE

server.port=8010
#spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=QAPDBS;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=QAPDBS;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://host.docker.internal:1433;databaseName=QAPDBS;encrypt=true;trustServerCertificate=true
#spring.datasource.url=jdbc:sqlserver://host.docker.internal;instanceName=SQLEXPRESS;databaseName=QAPDBS;encrypt=true;trustServerCertificate=true

spring.profiles.active=local

